<a href="https://colab.research.google.com/github/priyankasT16/Training/blob/master/DLbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np
# Create a dataset for the XOR function
x = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])
y = np.array([
    0,
    1,
    1,
    0
])
done = False
cycle = 1
while not done:
    print("Cycle #{}".format(cycle))
    cycle+=1
    model = Sequential()
    model.add(Dense(2, input_dim=2, activation='relu')) 
    model.add(Dense(1)) 
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(x,y,verbose=0,epochs=10000)
    pred=model.predict(x)
    done = pred[0]<0.01 and pred[3]<0.01 and pred[1] > 0.9 and pred[2] > 0.9 
    print(pred)

Cycle #1
[[0.49999997]
 [0.49999997]
 [0.49999997]
 [0.49999997]]
Cycle #2
[[4.9999994e-01]
 [4.9999994e-01]
 [1.0000000e+00]
 [2.9802322e-08]]
Cycle #3
[[0.49999997]
 [0.49999997]
 [1.        ]
 [0.        ]]
Cycle #4
[[7.4505806e-09]
 [9.9999946e-01]
 [9.9999994e-01]
 [5.3271651e-07]]


In [10]:
for layernum,layer in enumerate(model.layers):
  wts=layer.get_weights()[0]
  bias=layer.get_weights()[1]
  for toneuronno,bs in enumerate(bias):
    print(f'{layernum}B -> L{layernum+1} N {toneuronno}: {bs}')
  for fromNeuronNum, wgt in enumerate(wts):
        for toNeuronNum, wgt2 in enumerate(wgt):
            print(f'L {layernum} N {fromNeuronNum} -> L {layernum+1} N {toNeuronNum} = {wgt2}')


0B -> L1 N 0: 0.03358400613069534
0B -> L1 N 1: -0.0980440303683281
L 0 N 0 -> L 1 N 0 = -1.0055317878723145
L 0 N 0 -> L 1 N 1 = 0.981191098690033
L 0 N 1 -> L 1 N 0 = 0.6771824955940247
L 0 N 1 -> L 1 N 1 = -0.8414175510406494
1B -> L2 N 0: -0.0495937205851078
L 1 N 0 -> L 2 N 0 = 1.4767067432403564
L 1 N 1 -> L 2 N 0 = 1.188469409942627
