<a href="https://colab.research.google.com/github/priyankasT16/Training/blob/master/DLbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
import numpy as np
# Create a dataset for the XOR function
x = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])
y = np.array([
    0,
    1,
    1,
    0
])
done = False
cycle = 1
while not done:
    print("Cycle #{}".format(cycle))
    cycle+=1
    model = Sequential()
    model.add(Dense(2, input_dim=2, activation='relu')) 
    model.add(Dense(1)) 
    model.compile(loss='mean_squared_error', optimizer='adam')
    model.fit(x,y,verbose=0,epochs=10000)
    pred=model.predict(x)
    done = pred[0]<0.01 and pred[3]<0.01 and pred[1] > 0.9 and pred[2] > 0.9 
    print(pred)

Cycle #1
[[0.49999997]
 [0.49999997]
 [0.49999997]
 [0.49999997]]
Cycle #2
[[4.9999994e-01]
 [4.9999994e-01]
 [1.0000000e+00]
 [2.9802322e-08]]
Cycle #3
[[0.49999997]
 [0.49999997]
 [1.        ]
 [0.        ]]
Cycle #4
[[7.4505806e-09]
 [9.9999946e-01]
 [9.9999994e-01]
 [5.3271651e-07]]


In [0]:
for 